/** Generated by scripts/generate-og-images.mjs — do not edit by hand */
export const ogManifest = {
  "routes": {
    "/get-started": {
      "title": "Get Started · ReactTeacher",
      "description": "Setup, study paths, and how to get the most from ReactTeacher.",
      "ogImageId": "get-started"
    },
    "/js-basics": {
      "title": "JS Basics · ReactTeacher",
      "description": "JavaScript from zero: types, operators, if/for/while, arrays, then React-ready patterns.",
      "ogImageId": "js-basics"
    },
    "/challenges": {
      "title": "React Challenges · ReactTeacher",
      "description": "Hands-on React coding challenges from easy to very hard with acceptance criteria.",
      "ogImageId": "challenges"
    },
    "/flashcards": {
      "title": "Flashcards · ReactTeacher",
      "description": "Quick-review flashcards for hooks, patterns, performance, Next.js, and more.",
      "ogImageId": "flashcards"
    },
    "/react-patterns": {
      "title": "React Patterns · ReactTeacher",
      "description": "React component and state patterns with examples for interviews and production code.",
      "ogImageId": "react-patterns"
    },
    "/system-design": {
      "title": "System Design · ReactTeacher",
      "description": "Frontend system design problems and interview walkthroughs.",
      "ogImageId": "system-design"
    },
    "/flashcards/accessibility": {
      "title": "Accessibility · Flashcards",
      "description": "Study 15 flashcards on Accessibility for React interviews.",
      "ogImageId": "flashcards/accessibility"
    },
    "/flashcards/architecture": {
      "title": "Application Architecture · Flashcards",
      "description": "Study 15 flashcards on Application Architecture for React interviews.",
      "ogImageId": "flashcards/architecture"
    },
    "/flashcards/lifecycle": {
      "title": "Component Lifecycle · Flashcards",
      "description": "Study 10 flashcards on Component Lifecycle for React interviews.",
      "ogImageId": "flashcards/lifecycle"
    },
    "/flashcards/data-fetching": {
      "title": "Data Fetching & Management · Flashcards",
      "description": "Study 15 flashcards on Data Fetching & Management for React interviews.",
      "ogImageId": "flashcards/data-fetching"
    },
    "/flashcards/design-patterns": {
      "title": "Design Patterns · Flashcards",
      "description": "Study 15 flashcards on Design Patterns for React interviews.",
      "ogImageId": "flashcards/design-patterns"
    },
    "/flashcards/forms": {
      "title": "Forms & Validation · Flashcards",
      "description": "Study 14 flashcards on Forms & Validation for React interviews.",
      "ogImageId": "flashcards/forms"
    },
    "/flashcards/hooks": {
      "title": "Hooks · Flashcards",
      "description": "Study 14 flashcards on Hooks for React interviews.",
      "ogImageId": "flashcards/hooks"
    },
    "/flashcards/nextjs": {
      "title": "Next Framework · Flashcards",
      "description": "Study 15 flashcards on Next Framework for React interviews.",
      "ogImageId": "flashcards/nextjs"
    },
    "/flashcards/performance": {
      "title": "Performance Optimization · Flashcards",
      "description": "Study 15 flashcards on Performance Optimization for React interviews.",
      "ogImageId": "flashcards/performance"
    },
    "/flashcards/react-19": {
      "title": "React 19 · Flashcards",
      "description": "Study 15 flashcards on React 19 for React interviews.",
      "ogImageId": "flashcards/react-19"
    },
    "/flashcards/ecosystem": {
      "title": "React Ecosystem & Integration · Flashcards",
      "description": "Study 14 flashcards on React Ecosystem & Integration for React interviews.",
      "ogImageId": "flashcards/ecosystem"
    },
    "/flashcards/fundamentals": {
      "title": "React Fundamentals · Flashcards",
      "description": "Study 15 flashcards on React Fundamentals for React interviews.",
      "ogImageId": "flashcards/fundamentals"
    },
    "/flashcards/internals": {
      "title": "React Internals · Flashcards",
      "description": "Study 14 flashcards on React Internals for React interviews.",
      "ogImageId": "flashcards/internals"
    },
    "/flashcards/routing": {
      "title": "Routing & Navigation · Flashcards",
      "description": "Study 15 flashcards on Routing & Navigation for React interviews.",
      "ogImageId": "flashcards/routing"
    },
    "/flashcards/security": {
      "title": "Security Best Practices · Flashcards",
      "description": "Study 15 flashcards on Security Best Practices for React interviews.",
      "ogImageId": "flashcards/security"
    },
    "/flashcards/server-components": {
      "title": "Server Components & SSR · Flashcards",
      "description": "Study 15 flashcards on Server Components & SSR for React interviews.",
      "ogImageId": "flashcards/server-components"
    },
    "/flashcards/styling": {
      "title": "Styling in React · Flashcards",
      "description": "Study 15 flashcards on Styling in React for React interviews.",
      "ogImageId": "flashcards/styling"
    },
    "/flashcards/testing": {
      "title": "Testing React Applications · Flashcards",
      "description": "Study 15 flashcards on Testing React Applications for React interviews.",
      "ogImageId": "flashcards/testing"
    },
    "/flashcards/tools": {
      "title": "Tools & Build Pipeline · Flashcards",
      "description": "Study 15 flashcards on Tools & Build Pipeline for React interviews.",
      "ogImageId": "flashcards/tools"
    },
    "/flashcards/typescript": {
      "title": "TypeScript in React · Flashcards",
      "description": "Study 15 flashcards on TypeScript in React for React interviews.",
      "ogImageId": "flashcards/typescript"
    },
    "/challenges/easy": {
      "title": "Easy Challenges · ReactTeacher",
      "description": "19 easy React coding challenges with acceptance criteria and solutions.",
      "ogImageId": "challenges/easy"
    },
    "/challenges/easy/01-counter-component": {
      "title": "Counter Component · Easy",
      "description": "Easy React challenge: Counter Component. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/01-counter-component"
    },
    "/challenges/easy/02-shopping-cart-state": {
      "title": "Shopping Cart State · Easy",
      "description": "Easy React challenge: Shopping Cart State. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/02-shopping-cart-state"
    },
    "/challenges/easy/03-use-previous-hook": {
      "title": "usePrevious Hook · Easy",
      "description": "Easy React challenge: usePrevious Hook. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/03-use-previous-hook"
    },
    "/challenges/easy/04-event-handling": {
      "title": "Event Handling · Easy",
      "description": "Easy React challenge: Event Handling. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/04-event-handling"
    },
    "/challenges/easy/05-controlled-input-field": {
      "title": "Controlled Input Field · Easy",
      "description": "Easy React challenge: Controlled Input Field. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/05-controlled-input-field"
    },
    "/challenges/easy/06-fetching-data": {
      "title": "Fetching Data · Easy",
      "description": "Easy React challenge: Fetching Data. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/06-fetching-data"
    },
    "/challenges/easy/07-dynamic-list-rendering": {
      "title": "Dynamic List Rendering · Easy",
      "description": "Easy React challenge: Dynamic List Rendering. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/07-dynamic-list-rendering"
    },
    "/challenges/easy/08-use-interval-hook": {
      "title": "useInterval Hook · Easy",
      "description": "Easy React challenge: useInterval Hook. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/08-use-interval-hook"
    },
    "/challenges/easy/09-component-composition": {
      "title": "Component Composition · Easy",
      "description": "Easy React challenge: Component Composition. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/09-component-composition"
    },
    "/challenges/easy/10-focus-input-useref": {
      "title": "Focus an Input with useRef · Easy",
      "description": "Easy React challenge: Focus an Input with useRef. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/10-focus-input-useref"
    },
    "/challenges/easy/11-refactor-to-props": {
      "title": "Refactor to Props · Easy",
      "description": "Easy React challenge: Refactor to Props. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/11-refactor-to-props"
    },
    "/challenges/easy/12-build-a-clock": {
      "title": "Build a Clock · Easy",
      "description": "Easy React challenge: Build a Clock. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/12-build-a-clock"
    },
    "/challenges/easy/13-progress-bar-component": {
      "title": "Progress Bar Component · Easy",
      "description": "Easy React challenge: Progress Bar Component. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/13-progress-bar-component"
    },
    "/challenges/easy/14-performance-monitoring": {
      "title": "Performance Monitoring · Easy",
      "description": "Easy React challenge: Performance Monitoring. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/14-performance-monitoring"
    },
    "/challenges/easy/15-mouse-tracker": {
      "title": "MouseTracker · Easy",
      "description": "Easy React challenge: MouseTracker. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/15-mouse-tracker"
    },
    "/challenges/easy/16-simple-theme-switcher": {
      "title": "Simple Theme Switcher · Easy",
      "description": "Easy React challenge: Simple Theme Switcher. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/16-simple-theme-switcher"
    },
    "/challenges/easy/17-temperature-converter": {
      "title": "Temperature Converter · Easy",
      "description": "Easy React challenge: Temperature Converter. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/17-temperature-converter"
    },
    "/challenges/easy/18-theme-toggle": {
      "title": "Theme Toggle · Easy",
      "description": "Easy React challenge: Theme Toggle. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/18-theme-toggle"
    },
    "/challenges/easy/19-use-toggle-hook": {
      "title": "useToggle Hook · Easy",
      "description": "Easy React challenge: useToggle Hook. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/easy/19-use-toggle-hook"
    },
    "/challenges/medium": {
      "title": "Medium Challenges · ReactTeacher",
      "description": "26 medium React coding challenges with acceptance criteria and solutions.",
      "ogImageId": "challenges/medium"
    },
    "/challenges/medium/01-todo-list-manager": {
      "title": "Todo List Manager · Medium",
      "description": "Medium React challenge: Todo List Manager. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/01-todo-list-manager"
    },
    "/challenges/medium/02-image-carousel": {
      "title": "Image Carousel · Medium",
      "description": "Medium React challenge: Image Carousel. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/02-image-carousel"
    },
    "/challenges/medium/03-event-delegation": {
      "title": "Event Delegation · Medium",
      "description": "Medium React challenge: Event Delegation. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/03-event-delegation"
    },
    "/challenges/medium/04-memoizing-expensive-calculation": {
      "title": "Memoizing Expensive Calculation · Medium",
      "description": "Medium React challenge: Memoizing Expensive Calculation. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/04-memoizing-expensive-calculation"
    },
    "/challenges/medium/05-form-validation": {
      "title": "Form Validation · Medium",
      "description": "Medium React challenge: Form Validation. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/05-form-validation"
    },
    "/challenges/medium/06-nested-state-manager": {
      "title": "Nested State Manager · Medium",
      "description": "Medium React challenge: Nested State Manager. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/06-nested-state-manager"
    },
    "/challenges/medium/07-state-history-manager": {
      "title": "State History Manager · Medium",
      "description": "Medium React challenge: State History Manager. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/07-state-history-manager"
    },
    "/challenges/medium/08-advanced-theme-manager": {
      "title": "Advanced Theme Manager · Medium",
      "description": "Medium React challenge: Advanced Theme Manager. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/08-advanced-theme-manager"
    },
    "/challenges/medium/09-use-async-hook": {
      "title": "useAsync Hook · Medium",
      "description": "Medium React challenge: useAsync Hook. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/09-use-async-hook"
    },
    "/challenges/medium/10-use-reducer-implementation": {
      "title": "useReducer Implementation · Medium",
      "description": "Medium React challenge: useReducer Implementation. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/10-use-reducer-implementation"
    },
    "/challenges/medium/11-pagination-implementation": {
      "title": "Pagination Implementation · Medium",
      "description": "Medium React challenge: Pagination Implementation. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/11-pagination-implementation"
    },
    "/challenges/medium/12-theme-context": {
      "title": "Theme Context · Medium",
      "description": "Medium React challenge: Theme Context. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/12-theme-context"
    },
    "/challenges/medium/13-radiogroup-component": {
      "title": "RadioGroup Component · Medium",
      "description": "Medium React challenge: RadioGroup Component. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/13-radiogroup-component"
    },
    "/challenges/medium/14-fallback-ui-class-components": {
      "title": "Fallback UI (Error Boundaries) · Medium",
      "description": "Medium React challenge: Fallback UI (Error Boundaries). Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/14-fallback-ui-class-components"
    },
    "/challenges/medium/15-handling-api-errors": {
      "title": "Handling API Errors · Medium",
      "description": "Medium React challenge: Handling API Errors. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/15-handling-api-errors"
    },
    "/challenges/medium/16-cache-management": {
      "title": "Cache Management · Medium",
      "description": "Medium React challenge: Cache Management. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/16-cache-management"
    },
    "/challenges/medium/17-reusable-tabs-component": {
      "title": "Build a Reusable Tabs Component · Medium",
      "description": "Medium React challenge: Build a Reusable Tabs Component. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/17-reusable-tabs-component"
    },
    "/challenges/medium/18-share-state-with-context": {
      "title": "Share State with Context · Medium",
      "description": "Medium React challenge: Share State with Context. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/18-share-state-with-context"
    },
    "/challenges/medium/19-memo-prevent-rerenders": {
      "title": "Memo Usage: Prevent Unnecessary Re-renders · Medium",
      "description": "Medium React challenge: Memo Usage: Prevent Unnecessary Re-renders. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/19-memo-prevent-rerenders"
    },
    "/challenges/medium/20-multi-step-form-persistent-state": {
      "title": "Multi-step Form with Persistent State · Medium",
      "description": "Medium React challenge: Multi-step Form with Persistent State. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/20-multi-step-form-persistent-state"
    },
    "/challenges/medium/21-multiple-contexts": {
      "title": "Multiple Contexts · Medium",
      "description": "Medium React challenge: Multiple Contexts. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/21-multiple-contexts"
    },
    "/challenges/medium/22-reusable-input-component": {
      "title": "Build a Reusable Input Component · Medium",
      "description": "Medium React challenge: Build a Reusable Input Component. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/22-reusable-input-component"
    },
    "/challenges/medium/23-reusable-button-component": {
      "title": "Build a Reusable Button Component · Medium",
      "description": "Medium React challenge: Build a Reusable Button Component. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/23-reusable-button-component"
    },
    "/challenges/medium/24-reusable-drawer-component": {
      "title": "Build a Reusable Drawer Component · Medium",
      "description": "Medium React challenge: Build a Reusable Drawer Component. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/24-reusable-drawer-component"
    },
    "/challenges/medium/25-tic-tac-toe-game": {
      "title": "Build a Tic-Tac-Toe Game · Medium",
      "description": "Medium React challenge: Build a Tic-Tac-Toe Game. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/25-tic-tac-toe-game"
    },
    "/challenges/medium/26-multi-theme-manager": {
      "title": "Multi-Theme Manager · Medium",
      "description": "Medium React challenge: Multi-Theme Manager. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/medium/26-multi-theme-manager"
    },
    "/challenges/hard": {
      "title": "Hard Challenges · ReactTeacher",
      "description": "5 hard React coding challenges with acceptance criteria and solutions.",
      "ogImageId": "challenges/hard"
    },
    "/challenges/hard/01-timer-controls": {
      "title": "Timer Controls · Hard",
      "description": "Hard React challenge: Timer Controls. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/hard/01-timer-controls"
    },
    "/challenges/hard/02-multi-step-form-branching": {
      "title": "Multi-step Form with Branching Logic · Hard",
      "description": "Hard React challenge: Multi-step Form with Branching Logic. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/hard/02-multi-step-form-branching"
    },
    "/challenges/hard/03-prevent-unnecessary-rerenders": {
      "title": "Prevent Unnecessary Re-renders · Hard",
      "description": "Hard React challenge: Prevent Unnecessary Re-renders. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/hard/03-prevent-unnecessary-rerenders"
    },
    "/challenges/hard/04-dynamic-form-fields": {
      "title": "Dynamic Form Fields · Hard",
      "description": "Hard React challenge: Dynamic Form Fields. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/hard/04-dynamic-form-fields"
    },
    "/challenges/hard/05-art-drawing-tool": {
      "title": "Art Drawing Tool · Hard",
      "description": "Hard React challenge: Art Drawing Tool. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/hard/05-art-drawing-tool"
    },
    "/challenges/very-hard": {
      "title": "Very Hard Challenges · ReactTeacher",
      "description": "3 very hard React coding challenges with acceptance criteria and solutions.",
      "ogImageId": "challenges/very-hard"
    },
    "/challenges/very-hard/01-connect-four": {
      "title": "Connect Four · Very Hard",
      "description": "Very Hard React challenge: Connect Four. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/very-hard/01-connect-four"
    },
    "/challenges/very-hard/02-advanced-custom-hooks": {
      "title": "Advanced Custom Hooks · Very Hard",
      "description": "Very Hard React challenge: Advanced Custom Hooks. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/very-hard/02-advanced-custom-hooks"
    },
    "/challenges/very-hard/03-list-virtualization": {
      "title": "List Virtualization: Manual Virtual Scrolling · Very Hard",
      "description": "Very Hard React challenge: List Virtualization: Manual Virtual Scrolling. Practice with acceptance criteria and a solution walkthrough.",
      "ogImageId": "challenges/very-hard/03-list-virtualization"
    },
    "/system-design/infinite-scroll": {
      "title": "Twitter Feed · System Design",
      "description": "Frontend system design: Infinite Scroll Feed. Interview walkthrough on ReactTeacher.",
      "ogImageId": "system-design/infinite-scroll"
    },
    "/system-design/form-builder": {
      "title": "Form Builder · System Design",
      "description": "Frontend system design: Dynamic Form Generation and Validation. Interview walkthrough on ReactTeacher.",
      "ogImageId": "system-design/form-builder"
    },
    "/system-design/state-store": {
      "title": "State Store · System Design",
      "description": "Frontend system design: Custom State Management Implementation. Interview walkthrough on ReactTeacher.",
      "ogImageId": "system-design/state-store"
    },
    "/system-design/chat-application": {
      "title": "Chat Application · System Design",
      "description": "Frontend system design: WebSocket-based Chat App. Interview walkthrough on ReactTeacher.",
      "ogImageId": "system-design/chat-application"
    },
    "/system-design/auth-system": {
      "title": "Auth System · System Design",
      "description": "Frontend system design: Role-based Authentication System. Interview walkthrough on ReactTeacher.",
      "ogImageId": "system-design/auth-system"
    },
    "/system-design/google-docs-clone": {
      "title": "Google Docs Clone · System Design",
      "description": "Frontend system design: Real-time Collaboration Editor. Interview walkthrough on ReactTeacher.",
      "ogImageId": "system-design/google-docs-clone"
    },
    "/system-design/video-player": {
      "title": "Video Player · System Design",
      "description": "Frontend system design: Custom Video Player. Interview walkthrough on ReactTeacher.",
      "ogImageId": "system-design/video-player"
    },
    "/system-design/kanban-board": {
      "title": "Kanban Board · System Design",
      "description": "Frontend system design: Complex Drag-and-Drop Interactions. Interview walkthrough on ReactTeacher.",
      "ogImageId": "system-design/kanban-board"
    },
    "/react-patterns/compound-components": {
      "title": "Compound Components · React Patterns",
      "description": "React pattern guide: Shared implicit state via context. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/compound-components"
    },
    "/react-patterns/custom-hooks": {
      "title": "Custom Hooks · React Patterns",
      "description": "React pattern guide: Reusable stateful logic. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/custom-hooks"
    },
    "/react-patterns/container-presentational": {
      "title": "Container / Presentational · React Patterns",
      "description": "React pattern guide: Separate data from UI. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/container-presentational"
    },
    "/react-patterns/provider-context": {
      "title": "Provider / Context · React Patterns",
      "description": "React pattern guide: Share values without prop drilling. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/provider-context"
    },
    "/react-patterns/controlled-uncontrolled": {
      "title": "Controlled vs Uncontrolled · React Patterns",
      "description": "React pattern guide: Who owns form input state. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/controlled-uncontrolled"
    },
    "/react-patterns/composition": {
      "title": "Composition · React Patterns",
      "description": "React pattern guide: Children and slot props. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/composition"
    },
    "/react-patterns/state-reducer": {
      "title": "State Reducer · React Patterns",
      "description": "React pattern guide: Predictable state transitions. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/state-reducer"
    },
    "/react-patterns/render-props": {
      "title": "Render Props · React Patterns",
      "description": "React pattern guide: Inject state into JSX via functions. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/render-props"
    },
    "/react-patterns/higher-order-components": {
      "title": "Higher-Order Components · React Patterns",
      "description": "React pattern guide: Enhance components with wrappers. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/higher-order-components"
    },
    "/react-patterns/polymorphic-components": {
      "title": "Polymorphic Components · React Patterns",
      "description": "React pattern guide: Flexible as prop rendering. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/polymorphic-components"
    },
    "/react-patterns/headless-ui": {
      "title": "Headless UI · React Patterns",
      "description": "React pattern guide: Behavior without prescribed markup. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/headless-ui"
    },
    "/react-patterns/portals": {
      "title": "Portals · React Patterns",
      "description": "React pattern guide: Render outside the parent DOM tree. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/portals"
    },
    "/react-patterns/error-boundaries": {
      "title": "Error Boundaries · React Patterns",
      "description": "React pattern guide: Isolate render failures. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/error-boundaries"
    },
    "/react-patterns/lazy-suspense": {
      "title": "Lazy Loading & Suspense · React Patterns",
      "description": "React pattern guide: Code-split routes and features. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/lazy-suspense"
    },
    "/react-patterns/lifting-state-up": {
      "title": "Lifting State Up · React Patterns",
      "description": "React pattern guide: Shared state in a common ancestor. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/lifting-state-up"
    },
    "/react-patterns/optimistic-ui": {
      "title": "Optimistic UI · React Patterns",
      "description": "React pattern guide: Instant feedback before the server confirms. Examples and tradeoffs on ReactTeacher.",
      "ogImageId": "react-patterns/optimistic-ui"
    }
  }
} as const;
